name: release_github

on:
  workflow_dispatch:
    inputs:
      release:
        description: 'Release after build'
        required: true
        default: 'no'
  push:
    tags:
      - "*"

env:
  BUILD_PYTHON_VERSION: 3.9
  BUILD_POETRY_VERSION: 2.1.2

jobs:
  build_python:
    runs-on: ubuntu-latest
    env:
      POETRY_VIRTUALENVS_CREATE: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ env.BUILD_PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.BUILD_PYTHON_VERSION }}

      - name: Set up Poetry ${{ env.BUILD_POETRY_VERSION }}
        uses: abatilo/actions-poetry@v3
        with:
          poetry-version: ${{ env.BUILD_POETRY_VERSION }}
          poetry-plugins: "poetry-plugin-export"

      - name: Export requirements
        run: poetry export --without-hashes -f requirements.txt --output requirements.txt

      - name: Get Git commit timestamp
        run: echo "TIMESTAMP=$(git log -1 --pretty=%ct)" >> $GITHUB_ENV

      - name: Build project for distribution
        run: poetry build
        env:
          SOURCE_DATE_EPOCH: ${{ env.TIMESTAMP }}

      - name: Save release python packages
        uses: actions/upload-artifact@v4
        with:
          name: release_dist_python
          path: dist

  release:
    if: github.event_name == 'push' || github.event.inputs.release == 'yes'
    needs: [build_python]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
      - uses: actions/checkout@v4

      - name: Get tag version
        run: |
          APP_VERSION=$(sed -n 's/^version = "\([^"]\+\)"$/\1/p' pyproject.toml)
          echo "TAG_VERSION=v$APP_VERSION" >> $GITHUB_ENV

      - name: Load release python packages
        uses: actions/download-artifact@v4
        with:
          name: release_dist_python
          path: dist

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/*"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ env.TAG_VERSION }}
          draft: true
